// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modal': string;
  'modal-info': string;
  'modal-info-button': string;
  'modal-info-button-buttonLeft': string;
  'modal-info-button-buttonRight': string;
  'modal-info-img': string;
  'modal-info-text': string;
}
export const cssExports: CssExports;
export default cssExports;
